params:
  learner:
    hidden_dim: [128, 256, 512, 1024, 2048]
    layers: [1,2,3]
    name: lstm
    sequence_length: 10

experiments:
  run_folder: /media/npittaras/B47E380F7E37C8BE/Data/nle/preliminary_exps/
  results_file: "results_network_prelim.csv"
  # evaluation measures evaluation:
  measures: [f1-score]
  aggregation: [macro, micro]
  run_types: [run, majority]
  sources_dir:  /home/npittaras/Documents/project/nle-special/nlp-semantic-augmentation
  virtualenv:

dataset:
  name: 20newsgroups

embedding:
  aggregation: [pad, 10, first]
  dimension: 50
  name: glove
  sequence_length: 10

folders:
  embeddings: embeddings
  serialization: serialization
  results: results

log_level: info

train:
  batch_size: 50
  epochs: 50
  folds: 5
