# variable parameters
params:
  learner:
    hidden_dim: [128, 256, 512, 1024, 2048]
    layers: [1,2,3]
    name: mlp
    sequence_length: 10

# experiment parameters
experiments:
  run_folder: /path/to/runs
  # evaluation measures evaluation:
  measures: [f1-score]
  aggregation: [macro, micro]
  run_types: [run, majority]
  sources_dir:  /path/to/sources
  virtualenv:
  do_mail: False

dataset:
  name: 20newsgroups

representation:
  aggregation: [pad, 10, first]
  dimension: 50
  name: glove
  sequence_length: 10

folders:
  run: whatever
  serialization: "serialization"
  raw_data: raw_data


print:
  # evaluation metrics: f1, accuracy, precision, recall
  measures: ["f1-score"]
  # evaluation metric aggregations: macro, micro, weighted
  aggregations: ["macro", "micro"]
  # which run type is of interest
  # run: the actual run you are evaluating
  # majority: a majority classifier baseline
  # random: a random classifier baseline
  run_types: [run]
  # stats aggregating fold values
  stats: ["mean", "var"]



log_level: info

train:
  batch_size: 50
  epochs: 50
  folds: 5
